# Generated by Django 4.1.6 on 2023-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturer', models.CharField(max_length=225)),
                ('course', models.CharField(max_length=225)),
                ('link', models.CharField(max_length=225)),
                ('status', models.CharField(default='Live', max_length=225)),
            ],
        ),
    ]
