# Generated by Django 4.1.6 on 2023-08-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='question',
        ),
    ]
