# Generated by Django 4.1.6 on 2023-02-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=225)),
                ('lecturer', models.CharField(max_length=225)),
                ('file_name', models.CharField(max_length=225)),
            ],
        ),
    ]
