# Generated by Django 4.1.6 on 2023-02-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_coursematerials_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerials',
            name='semester',
            field=models.CharField(default='First Semester', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursematerials',
            name='file',
            field=models.FileField(unique=True, upload_to='course_materials/'),
        ),
    ]
