# Generated by Django 4.1.6 on 2023-02-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_coursematerials_semester_alter_coursematerials_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerials',
            name='semester',
        ),
    ]
