# Generated by Django 4.1.6 on 2023-06-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_uploadassignment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=225, unique=True)),
                ('submit_date', models.DateTimeField()),
                ('file', models.FileField(upload_to='submitted_assignments/')),
                ('student', models.CharField(max_length=225)),
            ],
        ),
    ]
